export const editStyles = {
  editContainer: {
    padding: 16,
    paddingTop: 30,
    paddingBottom: 28,
    marginTop: 0,
  },
  backRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 14,
  },
  backTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1F1F1F",
  },
  editAvatarWrap: {
    alignSelf: "center",
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: "#EDEDED",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  editAvatar: { width: 72, height: 72, borderRadius: 36 },
  cameraBadge: {
    position: "absolute",
    right: -2,
    bottom: -2,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#111",
  },
  inputLabel: {
    fontSize: 13,
    color: "#1F1F1F",
    fontWeight: "600",
    marginBottom: 6,
    marginTop: 6,
  },
  inputCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E6E6E6",
    paddingHorizontal: 10,
  },
  inputCardError: {
    borderColor: "#D44A4A",
  },
  errorText: {
    marginTop: 6,
    marginBottom: 4,
    fontSize: 12,
    color: "#D44A4A",
    fontWeight: "500",
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 6,
    paddingVertical: 12,
  },
  leftIcon: { width: 30, alignItems: "center" },
  input: {
    flex: 1,
    fontSize: 14,
    color: "#111",
    paddingVertical: 0,
  },
  saveBtnDark: {
    marginTop: 18,
    backgroundColor: "#111111",
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
  },
  saveTextDark: { color: "#FFFFFF", fontSize: 14, fontWeight: "600" },
} as const;
