/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/order` | `/order`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/service/all` | `/service/all`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/service/create-order` | `/service/create-order`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/service` | `/service`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/service/repairman-profile` | `/service/repairman-profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/service/select-repairman` | `/service/select-repairman`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/order` | `/order`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/service/all` | `/service/all`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/service/create-order` | `/service/create-order`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/service` | `/service`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/service/repairman-profile` | `/service/repairman-profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/service/select-repairman` | `/service/select-repairman`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/order${`?${string}` | `#${string}` | ''}` | `/order${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/service/all${`?${string}` | `#${string}` | ''}` | `/service/all${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/service/create-order${`?${string}` | `#${string}` | ''}` | `/service/create-order${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/service${`?${string}` | `#${string}` | ''}` | `/service${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/service/repairman-profile${`?${string}` | `#${string}` | ''}` | `/service/repairman-profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/service/select-repairman${`?${string}` | `#${string}` | ''}` | `/service/select-repairman${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/order` | `/order`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/service/all` | `/service/all`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/service/create-order` | `/service/create-order`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/service` | `/service`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/service/repairman-profile` | `/service/repairman-profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/service/select-repairman` | `/service/select-repairman`; params?: Router.UnknownInputParams; };
    }
  }
}
